# Generated by Django 5.0.6 on 2024-07-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('availability_weekdays', models.BooleanField(default=False)),
                ('availability_weekends', models.BooleanField(default=False)),
                ('skills', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
