# Generated by Django 5.0.6 on 2024-07-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='availability_weekdays',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='availability_weekends',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(default='Weekdays', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='additional_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
