# Generated by Django 5.0.6 on 2024-07-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_volunteer_availability_weekdays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='additional_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(max_length=255),
        ),
    ]
