# Generated by Django 5.0.6 on 2024-07-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_volunteer_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='additional_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(default='Weekdays', max_length=50),
        ),
    ]
