# Generated by Django 5.0.6 on 2024-07-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_volunteer_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='availability',
        ),
    ]
