# Generated by Django 5.0.6 on 2024-07-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_volunteer_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donated_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('vegetarian', 'vegetarian'), ('non-vegetarian', 'non-vegetarian')], max_length=20)),
                ('breakfast', models.BooleanField(default=False)),
                ('breakfast_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('breakfast_time', models.TimeField(blank=True, null=True)),
                ('lunch', models.BooleanField(default=False)),
                ('lunch_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('lunch_time', models.TimeField(blank=True, null=True)),
                ('dinner', models.BooleanField(default=False)),
                ('dinner_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('dinner_time', models.TimeField(blank=True, null=True)),
                ('meal_prepared', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('restaurant_address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
