# Generated by Django 5.0.6 on 2024-07-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_donated_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian')], max_length=10)),
                ('breakfast', models.BooleanField(default=False)),
                ('breakfast_quantity', models.IntegerField(blank=True, null=True)),
                ('breakfast_time', models.TimeField(blank=True, null=True)),
                ('lunch', models.BooleanField(default=False)),
                ('lunch_quantity', models.IntegerField(blank=True, null=True)),
                ('lunch_time', models.TimeField(blank=True, null=True)),
                ('dinner', models.BooleanField(default=False)),
                ('dinner_quantity', models.IntegerField(blank=True, null=True)),
                ('dinner_time', models.TimeField(blank=True, null=True)),
                ('meal_prepared', models.BooleanField(default=False)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('restaurant_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Donated_us',
        ),
    ]
