# Generated by Django 5.0.6 on 2024-07-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_donateddetails_delete_donation_alter_volunteer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donateddetails',
            old_name='email',
            new_name='res_email',
        ),
    ]
