# Generated by Django 5.0.7 on 2024-07-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_volunteer_email"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DonatedDetails",
            new_name="DonatedDetail",
        ),
    ]
