# Generated by Django 5.0.7 on 2024-07-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_rename_donateddetails_donateddetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donateddetail",
            name="breakfast_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="donateddetail",
            name="dinner_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="donateddetail",
            name="lunch_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="donateddetail",
            name="meal_prepared",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="donateddetail",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("non-vegetarian", "Non-Vegetarian"),
                ],
                max_length=100,
            ),
        ),
    ]
