# Generated by Django 5.0.7 on 2024-07-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_donateddetail_breakfast_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donateddetail",
            name="breakfast_time",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="donateddetail",
            name="dinner_time",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="donateddetail",
            name="lunch_time",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
