# Generated by Django 5.0.7 on 2024-07-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_donateddetail_breakfast_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donateddetail",
            name="phone_number",
            field=models.IntegerField(max_length=10),
        ),
    ]
