# Generated by Django 5.0.7 on 2024-08-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_donateddetail_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="donateddetail",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
