# Generated by Django 5.0.7 on 2024-08-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_donateddetail_is_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donateddetail",
            name="is_confirmed",
        ),
    ]
