# Generated by Django 5.0.7 on 2024-08-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_remove_donateddetail_is_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="donateddetail",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
